---
- name: Create /usr/share/man/man[1-8] subdirectories if necessary
  ansible.builtin.file:
    mode: 0755
    path: /usr/share/man/man{{ item }}
    state: directory
  loop: "{{ range(1, 9) | list }}"
