---
# tasks file for openjdk

- name: Load var file with package names based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

# The debian:<release>-slim Docker images are missing the
# /usr/share/man/man[1-8] directories, which causes some packages
# (including openjdk-jdk) to fail to install.
- name: Add missing man directories if necessary
  include_tasks:
    file: add_missing_man_dirs.yml
  when: ansible_distribution == "Debian"

- name: Install OpenJDK
  package:
    name: "{{ package_names }}"
