---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

# The debian:<release>-slim Docker images are missing the
# /usr/share/man/man[1-8] directories, which causes some packages
# (including openjdk-jdk) to fail to install.
- name: Add missing man directories for Debian
  ansible.builtin.include_tasks:
    file: add_missing_man_dirs.yml
  when: ansible_os_family == "Debian"

# This seems to be necessary for Debian Buster.  If I don't do this
# then the installation of OpenJDK fails.  For (minimally) more
# information see here:
# https://stackoverflow.com/questions/76872534/problem-installing-ca-certificates-java-package-within-debian-bookworm-docker-im
- name: Install jing
  ansible.builtin.package:
    name:
      - jing
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "buster"

- name: Install OpenJDK
  ansible.builtin.package:
    name: "{{ package_names }}"
