---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

# The debian:<release>-slim Docker images are missing the
# /usr/share/man/man[1-8] directories, which causes some packages
# (including openjdk-jdk) to fail to install.
- name: Add missing man directories for Debian
  ansible.builtin.include_tasks:
    file: add_missing_man_dirs.yml
  when: ansible_distribution == "Debian"

- name: Install OpenJDK
  ansible.builtin.package:
    name: "{{ package_names }}"

# By default OpenJDK 17 is being used on Kali Linux.  Neo4j <5
# requires OpenJDK 11.
#
# TODO: This block can be removed once we upgrade to Neo4j version 5,
# as discussed in cisagov/kali-packer#136.
- name: Configure alternatives for Kali
  ansible.builtin.include_tasks:
    file: configure_alternatives.yml
  when: ansible_distribution == "Kali"
