---
# The Debian images we are using require a cache update before they
# can install anything.
- name: Group hosts by OS distribution
  hosts: all
  tasks:
    - name: Group hosts by OS distribution
      group_by:
        key: os_{{ ansible_os_family }}
- name: Update apt cache (Debian)
  hosts: os_Debian:os_Kali_GNU_Linux
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
